apiVersion: v1
kind: Service
metadata:
  name: deployment-service
  namespace: default
  labels:
    app: deployment-service
spec:
  selector:
    app: deployment-service
  ports:
    - protocol: TCP
      port: 7083
      targetPort: 7083
  type: ClusterIP
