apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrastructure-service
  namespace: default
  labels:
    app: infrastructure-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: infrastructure-service
  template:
    metadata:
      labels:
        app: infrastructure-service
    spec:
      containers:
      - name: infrastructure-service
        image: soben10/infrastructure-service:latest
        ports:
        - containerPort: 7082
        env:
        - name: DB_URL
          value: "jdbc:postgresql://postgres:5432/production"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: JWT_ISSUER_URI
          value: "http://identity-service:8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "*"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: "always"
          httpGet:
            path: /actuator/health
            port: 7082
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 7082
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        resources:
          requests:
            memory: "300Mi"
            cpu: "250m"
          limits:
            memory: "768Mi"
            cpu: "600m"
