apiVersion: v1
kind: Service
metadata:
  name: workspace-service
  namespace: default
  labels:
    app: workspace-service
spec:
  selector:
    app: workspace-service
  ports:
    - protocol: TCP
      port: 7081
      targetPort: 7081
  type: ClusterIP
