apiVersion: v1
kind: Service
metadata:
  name: cloudinator-ui
  namespace: default
  labels:
    app: cloudinator-ui
spec:
  selector:
    app: cloudinator-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
